package utility;

import server.AppServer;

import java.sql.*;

public class DatabaseHandler {
    // Table name
    public static final String LAB_TABLE = "lab_work";
    public static final String USER_TABLE = "my_user";
    public static final String COORDINATES_TABLE = "coordinates";
    public static final String DISCIPLINE_TABLE = "discipline";
    // LAB_TABLE column names
    public static final String LAB_TABLE_ID_COLUMN = "id";
    public static final String LAB_TABLE_NAME_COLUMN = "name";
    public static final String LAB_TABLE_CREATION_DATE_COLUMN = "creation_date";
    public static final String LAB_TABLE_MINIMAL_POINT_COLUMN = "minimal_point";
    public static final String LAB_TABLE_TUNED_IN_WORK_COLUMN = "tuned_in_works";
    public static final String LAB_TABLE_AVERAGE_POINT_COLUMN = "average_point";
    public static final String LAB_TABLE_DIFFICULTY_COLUMN = "difficulty";
    public static final String LAB_TABLE_DISCIPLINE_ID_COLUMN = "discipline_id";
    public static final String LAB_TABLE_USER_ID_COLUMN = "user_id";
    // USER_TABLE column names
    public static final String USER_TABLE_ID_COLUMN = "id";
    public static final String USER_TABLE_USERNAME_COLUMN = "username";
    public static final String USER_TABLE_PASSWORD_COLUMN = "password";
    // COORDINATES_TABLE column names
    public static final String COORDINATES_TABLE_ID_COLUMN = "id";
    public static final String COORDINATES_TABLE_LAB_WORK_ID_COLUMN = "lab_work_id";
    public static final String COORDINATES_TABLE_X_COLUMN = "x";
    public static final String COORDINATES_TABLE_Y_COLUMN = "y";
    // DISCIPLINE_TABLE column names
    public static final String DISCIPLINE_TABLE_ID_COLUMN = "id";
    public static final String DISCIPLINE_TABLE_NAME_COLUMN = "name";
    public static final String DISCIPLINE_TABLE_LABS_COUNT_COLUMN = "labs_count";

    private final String JDBC_DRIVER = "org.postgresql.Driver";

    private final String url;
    private final String user;
    private final String password;

    private Connection connection;

    public DatabaseHandler(String url, String user, String password) {
        this.url = url;
        this.user = user;
        this.password = password;

        connectToDB();
    }

    private void connectToDB() {
        try {
            Class.forName(JDBC_DRIVER);
            connection = DriverManager.getConnection(url, user, password);
            Outputer.println("Database connection established.");
            AppServer.LOGGER.info("Соединение с базой данных установлено.");
        } catch (SQLException exception) {
            Outputer.printError("Произошла ошибка при подключении к базе данных!");
            AppServer.LOGGER.severe("Произошла ошибка при подключении к базе данных!");
        } catch (ClassNotFoundException exception) {
            Outputer.printError("Драйвер управления базой дынных не найден!");
            AppServer.LOGGER.severe("Драйвер управления базой дынных не найден!");
        }
    }

    public PreparedStatement getPreparedStatement(String sqlStatement, boolean generateKeys) throws SQLException {
        PreparedStatement preparedStatement;
        try {
            if (connection == null) throw new SQLException();
            int autoGeneratedKeys = generateKeys ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS;
            preparedStatement = connection.prepareStatement(sqlStatement, autoGeneratedKeys);
            AppServer.LOGGER.info("Подготовлен SQL запрос '" + sqlStatement + "'.");
            return preparedStatement;
        } catch (SQLException exception) {
            AppServer.LOGGER.severe("Произошла ошибка при подготовке SQL запроса '" + sqlStatement + "'.");
            if (connection == null) AppServer.LOGGER.severe("Соединение с базой данных не установлено!");
            throw new SQLException(exception);
        }
    }

    public void closePreparedStatement(PreparedStatement sqlStatement) {
        if (sqlStatement == null) return;
        try {
            sqlStatement.close();
            AppServer.LOGGER.info("Закрыт SQL запрос '" + sqlStatement + "'.");
        } catch (SQLException exception) {
            AppServer.LOGGER.severe("Произошла ошибка при закрытии SQL запроса '" + sqlStatement + "'.");
        }
    }

    /**
     * Close connection to database.
     */
    public void closeConnection() {
        if (connection == null) return;
        try {
            connection.close();
            Outputer.println("Соединение с базой данных разорвано.");
            AppServer.LOGGER.info("Соединение с базой данных разорвано.");
        } catch (SQLException exception) {
            Outputer.printError("Произошла ошибка при разрыве соединения с базой данных!");
            AppServer.LOGGER.severe("Произошла ошибка при разрыве соединения с базой данных!");
        }
    }

    /**
     * Set commit mode of database.
     */
    public void setCommitMode() {
        try {
            if (connection == null) throw new SQLException();
            connection.setAutoCommit(false);
        } catch (SQLException exception) {
            AppServer.LOGGER.severe("Произошла ошибка при установлении режима транзакции базы данных!");
        }
    }

    /**
     * Set normal mode of database.
     */
    public void setNormalMode() {
        try {
            if (connection == null) throw new SQLException();
            connection.setAutoCommit(true);
        } catch (SQLException exception) {
            AppServer.LOGGER.severe("Произошла ошибка при установлении нормального режима базы данных!");
        }
    }

    /**
     * Commit database status.
     */
    public void commit() {
        try {
            if (connection == null) throw new SQLException();
            connection.commit();
        } catch (SQLException exception) {
            AppServer.LOGGER.severe("Произошла ошибка при подтверждении нового состояния базы данных!");
        }
    }

    /**
     * Roll back database status.
     */
    public void rollback() {
        try {
            if (connection == null) throw new SQLException();
            connection.rollback();
        } catch (SQLException exception) {
            AppServer.LOGGER.severe("Произошла ошибка при возврате исходного состояния базы данных!");
        }
    }

    /**
     * Set save point of database.
     */
    public void setSavepoint() {
        try {
            if (connection == null) throw new SQLException();
            connection.setSavepoint();
        } catch (SQLException exception) {
            AppServer.LOGGER.severe("Произошла ошибка при сохранении состояния базы данных!");
        }
    }
}
